meta_product_name: "Yield"
meta_title: "Yield - Gain control of your economy"
meta_description: "Yield helps you get your personal finances in order."
meta_image: "cover.png" # should exist in `app/assets/images/`
